# Generated by Django 3.0.7 on 2020-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
